// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC71p7Q9MswiBIgivdiPRYnSxRCNILD3tA',
    appId: '1:183829733604:web:461f1c333f85d60ce48cf1',
    messagingSenderId: '183829733604',
    projectId: 'khojmitra-ai',
    authDomain: 'khojmitra-ai.firebaseapp.com',
    storageBucket: 'khojmitra-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiyPTwTNAmzFMkEcsjBqfF8p-Yv1RWTGo',
    appId: '1:183829733604:android:65a020b84f51b67be48cf1',
    messagingSenderId: '183829733604',
    projectId: 'khojmitra-ai',
    storageBucket: 'khojmitra-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVwrRsQrXAyJVVfcy48ffeJz8-DPzMM6o',
    appId: '1:183829733604:ios:6098c2a5b41fdeabe48cf1',
    messagingSenderId: '183829733604',
    projectId: 'khojmitra-ai',
    storageBucket: 'khojmitra-ai.firebasestorage.app',
    iosBundleId: 'com.example.khojmitra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVwrRsQrXAyJVVfcy48ffeJz8-DPzMM6o',
    appId: '1:183829733604:ios:6098c2a5b41fdeabe48cf1',
    messagingSenderId: '183829733604',
    projectId: 'khojmitra-ai',
    storageBucket: 'khojmitra-ai.firebasestorage.app',
    iosBundleId: 'com.example.khojmitra',
  );
}
